const { uploadImage } = require('../../lib/whatsapp-media');
const { sendImage } = require('../../lib/send-message');

async function generateImage(prompt) {
  // Pollinations.ai — gratis, gak butuh API key
  const encoded = encodeURIComponent(prompt);
  const seed = Math.floor(Math.random() * 1000000);
  const url = `https://image.pollinations.ai/prompt/${encoded}?width=1024&height=1024&nologo=true&seed=${seed}`;

  const res = await fetch(url, {
    headers: { 'User-Agent': 'Mozilla/5.0 PanzzBot/1.0' },
    signal: AbortSignal.timeout(60000),
  });
  if (!res.ok) throw new Error(`Pollinations error (${res.status})`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length < 1000) throw new Error('Hasil gambar kosong');
  return buf;
}

module.exports = {
  name: 'img',
  alias: ['image', 'gambar', 'ai-image'],
  category: 'ai',
  description: 'Generate gambar pake AI (Pollinations)',

  async run({ from, args, sendMessage }) {
    if (!args?.[0]) {
      await sendMessage(from,
        '📝 Format: img <deskripsi>\n\n' +
        '*Contoh:*\n' +
        'img kucing pake topi koboi\n' +
        'img pemandangan gunung saat sunrise\n' +
        'img robot lagi ngopi di cafe'
      );
      return;
    }

    const prompt = args.join(' ');
    await sendMessage(from, `🎨 Lagi bikin gambar: _"${prompt}"_...\n\n_(butuh 10-30 detik)_`);

    try {
      const imgBuffer = await generateImage(prompt);
      const mediaId = await uploadImage(imgBuffer, 'ai-image.jpg');
      await sendImage(from, mediaId, `🎨 ${prompt}\n\n_Generated by Pollinations AI_`);
    } catch (e) {
      console.error('Img error:', e.message);
      await sendMessage(from, `❌ Gagal bikin gambar: ${e.message}`);
    }
  },
};
